---
galaxy_info:
  author: Daniel Hormos
  description: Baseline configuration and SSH hardening for Linux servers
  company: Personal lab
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - baseline
    - hardening
    - security

dependencies: []
